// src/components/HomeHero.jsx

import { useApi } from "@/hooks/useResources"
import SearchActorForm from "./searchActorForm"
import { useEffect } from "react"

export default function HomeHero() {

    // useEffect(() => console.log(categories.data.categories[0]))

    return (
      <div className="relative isolate overflow-hidden bg-gray-900 py-24 sm:py-32">
        <img
          src="https://images.unsplash.com/photo-1521737604893-d14cc237f11d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&crop=focalpoint&fp-y=.8&w=2830&h=1500&q=80&blend=111827&sat=-100&exp=15&blend-mode=multiply"
          alt=""
          className="absolute inset-0 -z-10 h-full w-full object-cover"
        />
        <div
          className="hidden sm:absolute sm:-top-10 sm:right-1/2 sm:-z-10 sm:mr-10 sm:block sm:transform-gpu sm:blur-3xl"
          aria-hidden="true"
        >
          <div
            className="aspect-[1097/845] w-[68.5625rem] bg-gradient-to-tr from-[#1d6f30] to-[#21b042] opacity-20"
            style={{
              clipPath:
                'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)',
            }}
          />
        </div>
        <div
          className="absolute -top-52 left-1/2 -z-10 -translate-x-1/2 transform-gpu blur-3xl sm:top-[-28rem] sm:ml-16 sm:translate-x-0 sm:transform-gpu"
          aria-hidden="true"
        >
          <div
            className="aspect-[1097/845] w-[68.5625rem] bg-gradient-to-tr from-[#1d6f30] to-[#21b042] opacity-20"
            style={{
              clipPath:
                'polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)',
            }}
          />
        </div>
        <div className="mx-auto max-w-7xl px-6 lg:px-8">
          <div className="mx-auto max-w-2xl lg:mx-0">
            <h2 className="text-4xl font-bold tracking-tight text-white sm:text-6xl">ACTEURS AGRICOLES DU BENIN</h2>
            <p className="mt-6 text-lg leading-8 text-gray-300">
            
                La Chambre Nationale d’Agriculture en route pour mettre en place
                un système d’information de marché grâce à l’appui technique du
                Ministère de l’Agriculture et l’appui financier du PARASEP à travers
                un financement de l’Union européenne et de l’Agence f rançaise de
                Développement.

            </p>
          </div>
        </div>

        <div className="mx-auto max-w-7xl px-6 lg:px-8 py-6 lg:py-8">
          <div className="mx-auto max-w-2xl lg:mx-0">
            
            <SearchActorForm/>

          </div>
        </div>

      </div>
    )
  }

// src/components/HomeHero.vue
<template>
    <div class="relative isolate overflow-hidden bg-green-700 py-20 sm:py-32">

      <img :src="bgimg" alt="" class="absolute inset-0 -z-40 h-full w-full object-cover" />
      
      <div class="absolute inset-0 -z-40 h-full w-full object-cover bg-gradient-to-t from-green-700/95 to-green-300/25"></div>

      <div class="mx-auto max-w-7xl px-6 lg:px-8">
        <div class="mx-auto max-w-2xl lg:mx-0">
          <h2 class="text-4xl font-bold tracking-tight text-white sm:text-6xl">ACTEURS AGRICOLES DU BENIN</h2>
          <p class="mt-6 text-xl leading-8 text-gray-300">
            La Chambre Nationale d’Agriculture en route pour mettre en place
                un système d’information de marché grâce à l’appui technique du
                Ministère de l’Agriculture et l’appui financier du PARASEP à travers
                un financement de l’Union européenne et de l’Agence f rançaise de
                Développement.
          </p>
        </div>
      </div>

      <div class="mx-auto max-w-7xl px-6 lg:px-8 py-6 lg:py-8">
        <SearchHero/>
      </div>

    </div>
</template>

<script>

import SearchHero from "./SearchHero.vue"
import bgimg from "@/images/background_image.png"

export default {
  name: 'HeroHome',
  components: {
    SearchHero
  },
  data () {
    return {

      bgimg : bgimg

    }
  }
}

</script>
